FROM pytorch/pytorch:1.13.1-cuda11.6-cudnn8-runtime

ADD requirements.txt .

# Dependencies
RUN apt-get update && apt-get install -y git ffmpeg &&\
         pip install --user --no-cache-dir -r requirements.txt 

WORKDIR /usr/src/app

ADD voice/ ./voice/
ADD config.yml .

CMD ["python3", "./voice/voice.py"]
