# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: subtitles.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fsubtitles.proto\";\n\x0fGenerateRequest\x12\x13\n\x0bsource_file\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65stin_file\x18\x02 \x01(\t\"\x07\n\x05\x45mpty23\n\tSubtitles\x12&\n\x08Generate\x12\x10.GenerateRequest\x1a\x06.Empty\"\x00\x62\x06proto3')



_GENERATEREQUEST = DESCRIPTOR.message_types_by_name['GenerateRequest']
_EMPTY = DESCRIPTOR.message_types_by_name['Empty']
GenerateRequest = _reflection.GeneratedProtocolMessageType('GenerateRequest', (_message.Message,), {
  'DESCRIPTOR' : _GENERATEREQUEST,
  '__module__' : 'subtitles_pb2'
  # @@protoc_insertion_point(class_scope:GenerateRequest)
  })
_sym_db.RegisterMessage(GenerateRequest)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'subtitles_pb2'
  # @@protoc_insertion_point(class_scope:Empty)
  })
_sym_db.RegisterMessage(Empty)

_SUBTITLES = DESCRIPTOR.services_by_name['Subtitles']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GENERATEREQUEST._serialized_start=19
  _GENERATEREQUEST._serialized_end=78
  _EMPTY._serialized_start=80
  _EMPTY._serialized_end=87
  _SUBTITLES._serialized_start=89
  _SUBTITLES._serialized_end=140
# @@protoc_insertion_point(module_scope)
