# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: subtitles.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fsubtitles.proto\"(\n\x18GenerateSubtitlesRequest\x12\x0c\n\x04path\x18\x01 \x01(\t\")\n\x19GenerateSubtitlesResponse\x12\x0c\n\x04path\x18\x01 \x01(\t2P\n\tSubtitles\x12\x43\n\x08Generate\x12\x19.GenerateSubtitlesRequest\x1a\x1a.GenerateSubtitlesResponse\"\x00\x62\x06proto3')



_GENERATESUBTITLESREQUEST = DESCRIPTOR.message_types_by_name['GenerateSubtitlesRequest']
_GENERATESUBTITLESRESPONSE = DESCRIPTOR.message_types_by_name['GenerateSubtitlesResponse']
GenerateSubtitlesRequest = _reflection.GeneratedProtocolMessageType('GenerateSubtitlesRequest', (_message.Message,), {
  'DESCRIPTOR' : _GENERATESUBTITLESREQUEST,
  '__module__' : 'subtitles_pb2'
  # @@protoc_insertion_point(class_scope:GenerateSubtitlesRequest)
  })
_sym_db.RegisterMessage(GenerateSubtitlesRequest)

GenerateSubtitlesResponse = _reflection.GeneratedProtocolMessageType('GenerateSubtitlesResponse', (_message.Message,), {
  'DESCRIPTOR' : _GENERATESUBTITLESRESPONSE,
  '__module__' : 'subtitles_pb2'
  # @@protoc_insertion_point(class_scope:GenerateSubtitlesResponse)
  })
_sym_db.RegisterMessage(GenerateSubtitlesResponse)

_SUBTITLES = DESCRIPTOR.services_by_name['Subtitles']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GENERATESUBTITLESREQUEST._serialized_start=19
  _GENERATESUBTITLESREQUEST._serialized_end=59
  _GENERATESUBTITLESRESPONSE._serialized_start=61
  _GENERATESUBTITLESRESPONSE._serialized_end=102
  _SUBTITLES._serialized_start=104
  _SUBTITLES._serialized_end=184
# @@protoc_insertion_point(module_scope)
